### ISSUE TITLE
作业1

### ISSUE THREAD

**Issue by cassiuschen** [iloveivyxuan/ruby-learning#1]
阅读《Programming Ruby》第二章，完成以下作业：

鸡兔同笼问题： 从命令行运行该程序，带有两个参数，第一个参数是头的数量，第二个参数是脚的数量，分别打印出鸡和兔的数量。
如：
```sh
$ ruby c&r.rb 7 22
Chicken: 3
Rabbit: 4
```

**Comment by iloveivyxuan** [comment]
1eb117e4f6a53283d553dc88c9e6f01b17d18649

**Comment by cassiuschen** [comment]
看我写的评论哦~
